version: '3.5'
services:
  basic-node-gql-mongo:
    image: mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
    - basic-node-gql-mongo:/data/db
    ports:
    - "27022:27017"

volumes:
  basic-node-gql-mongo:
